Accessibility Fork
adobe-accessibility/Accessible-Mega-Menu pull request #66
Opened 2020-01-24 00:31 UTC by maedi

A slew of accessibility improvements in one easy to merge pull request.

- Handle enter event on open top level link as escape event. #61
- Move aria-expanded from panel to top level link #62
- On enter activate top level link if it has no panel #63
- Fix mistargeting of topnav link when no panel #65

2020-02-25 15:58 UTC, m80her commented
works for me - nice job @maedi :)

2020-02-25 16:44 UTC, m80her commented
> works for me - nice job @maedi :)

@maedi - just noticed a slight quirk when using the up arrow key to close a subnav - the previous top level item (to the left with a subnav) receives the 'open' class and it's subnav is revealed.

2020-03-02 00:02 UTC, maedi commented
I'm not sure I can replicate your issue @m80her, are you able to attach a screenshot?

2020-03-11 13:30 UTC, m80her commented
@maedi makes sense - check out my live implementation and see if it's working as expected for you. Also I've noticed aria-hidden not changing to false when sub-nav is open - still investigating https://cadentgas.com/

2020-03-11 13:44 UTC, m80her commented on js/jquery-accessibleMegaMenu.js
> +                    .closest('.' + settings.panelClass)
.closest() doesn't trigger the addClass or aria-hidden toggle for me
changing this to .siblings() works

2020-03-11 13:55 UTC, m80her commented on js/jquery-accessibleMegaMenu.js
> +                    .closest('.' + settings.panelClass)
changing .closest() to .siblings() in all instances where settings.panelClass is adding/removing settings.openClass and toggling aria-hidden fixes this

2020-07-17 08:17 UTC, maedi commented
@m80her It's correctly toggling `[aria-expanded]` on the top level link and correctly toggling `[aria-hidden]` on its sub nav for me. That being said `siblings()` works for me too. So if your way works for both of us let's use that.

2020-08-21 06:46 UTC, maedi commented
Have removed `aria-pressed` attribute from the mobile menu toggle button. This change is recommended by a recent accessibility report that says:
> The main menu button on the mobile website has both the aria-expanded and aria-pressed attributes. The aria-pressed attribute should not be used for an accordion button. Screen readers will sometimes state "on" or "off" when expanding/collapsing the button, which is less useful than hearing "expanded" or "collapsed".

Would really appreciate if someone could take a look at this pull request. Many hours have been spent testing and improving the megamenu to meed modern accessibility requirements.

It is used in production on a few real world sites:
* https://www.ag.gov.au/
* https://www.acecqa.gov.au/
* https://cadentgas.com/ (nice job @m80her) 

With more sites in the pipeline. Well and truly battle tested.

2020-12-04 22:46 UTC, majornista commented on js/jquery-accessibleMegaMenu.js
> +            if (typeof window.cvox !== 'undefined' && window.cvox == true) {
Feels a bit odd to test truthiness of ChromeVox object using `window.cvox == true`.

2020-12-04 23:03 UTC, majornista requested changes
This all seems ok with the exception of the test for `window.cvox`.

2020-12-07 14:28 UTC, merged

2020-12-09 04:34 UTC, maedi commented
Thanks very much for merging @majornista and thank you for fixing the `window.cvox` issue in:
https://github.com/adobe-accessibility/Accessible-Mega-Menu/commit/5c070bc9011f125ae337cbb952749b44e0f86d54